name: CKA Certification Participation Scripts

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-cka-practice-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      # skip uploading test logs step 
      # - name: Upload Test Logs (Optional)
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: cka-test-logs
      #     path: logs/